title: Punit Arani
email: punitsai36@gmail.com
description: Software Engineer (Backend, Embedded Firmware, and Machine Learning)

github_username:  punitarani
linkedin_username: punitarani

theme: minima

collections:
  hackathons:
    output: true
  notes:
    output: true
  projects:
    output: true
  research:
    output: true
